# Generated by Django 5.2 on 2025-04-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aberto', 'Em aberto'), ('rascunho', 'Rascunho'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('pago', 'Pago'), ('enviado', 'Enviado')], default='aberto', max_length=50),
            preserve_default=False,
        ),
    ]
